### ISSUE TITLE
Provide an option to copy all branches from template and not just the default branch while creating a repo from template.

### ISSUE THREAD

**Issue by gushob21** [operatehappy/terraform-github-repository#28]
github now provides a checkbox "Include all branches" while creating a new repo from a template. This copies all branches from the template to the new repo. Currently, terraform supports creating a repo from template but copies only the default branch. There should be an option in terraform that allows the user to copy all branches.

# Expected Behavior

All branches from the templates can be copied to the new repo

## Current Behavior

Only the default branch is copied to the new repo

## Environment

1.) Output of `terraform version` incl. provider(s):

```sh

```

2.) Version of the module: ``

3.) Any other relevant environment information:

```sh

```

**Comment by ksatirli** [comment]
Hello @gushob21 - thanks for reporting this.

I see you requested this same feature in the upstream provider at https://github.com/integrations/terraform-provider-github/issues/1241.

Until this feature is made available in the provider itself, I cannot add it to this module, so I will close this for now.
